import { GradeType, GenreType } from '../_lib/types/cardType'

interface CardListType {
  imageUrl: string
  nickName: string
  id: number
  userId: number
  name: string
  price: number
  grade: GradeType
  genre: string
  totalQuantity: number
  remainingQuantity: number
  createdDate: string
  updatedDate: string
  method: 'sale' | 'exchange'
}

export const CARDS_LIST: CardListType[] = [
  {
    imageUrl: '/images/image1.png',
    nickName: 'Nick1',
    id: 1,
    userId: 1,
    name: 'Card1',
    price: 100,
    grade: 'common',
    genre: 'Fantasy',
    totalQuantity: 100,
    remainingQuantity: 0,
    createdDate: '2023-01-01',
    updatedDate: '2023-01-02',
    method: 'sale',
  },
  {
    imageUrl: '/images/image2.png',
    nickName: 'Nick2',
    id: 2,
    userId: 2,
    name: 'Card2',
    price: 200,
    grade: 'rare',
    genre: 'Sci-Fi',
    totalQuantity: 150,
    remainingQuantity: 75,
    createdDate: '2023-01-03',
    updatedDate: '2023-01-04',
    method: 'exchange',
  },
  {
    imageUrl: '/images/image2.png',
    nickName: 'Nick3',
    id: 3,
    userId: 3,
    name: 'Card3',
    price: 300,
    grade: 'super_rare',
    genre: 'Horror',
    totalQuantity: 200,
    remainingQuantity: 100,
    createdDate: '2023-01-05',
    updatedDate: '2023-01-06',
    method: 'exchange',
  },
  {
    imageUrl: '/images/image2.png',
    nickName: 'Nick4',
    id: 4,
    userId: 4,
    name: 'Card4',
    price: 400,
    grade: 'legendary',
    genre: 'Romance',
    totalQuantity: 250,
    remainingQuantity: 125,
    createdDate: '2023-01-07',
    updatedDate: '2023-01-08',
    method: 'sale',
  },
  {
    imageUrl: '/images/image2.png',
    nickName: 'Nick49',
    id: 5,
    userId: 5,
    name: 'Card49',
    price: 4900,
    grade: 'common',
    genre: 'Adventure',
    totalQuantity: 490,
    remainingQuantity: 245,
    createdDate: '2023-02-05',
    updatedDate: '2023-02-06',
    method: 'sale',
  },
  {
    imageUrl: '/images/image1.png',
    nickName: 'Nick1',
    id: 1,
    userId: 1,
    name: 'Card1',
    price: 100,
    grade: 'common',
    genre: 'Fantasy',
    totalQuantity: 100,
    remainingQuantity: 0,
    createdDate: '2023-01-01',
    updatedDate: '2023-01-02',
    method: 'sale',
  },
  {
    imageUrl: '/images/image2.png',
    nickName: 'Nick2',
    id: 2,
    userId: 2,
    name: 'Card2',
    price: 200,
    grade: 'rare',
    genre: 'Sci-Fi',
    totalQuantity: 150,
    remainingQuantity: 75,
    createdDate: '2023-01-03',
    updatedDate: '2023-01-04',
    method: 'exchange',
  },
  {
    imageUrl: '/images/image2.png',
    nickName: 'Nick3',
    id: 3,
    userId: 3,
    name: 'Card3',
    price: 300,
    grade: 'super_rare',
    genre: 'Horror',
    totalQuantity: 200,
    remainingQuantity: 100,
    createdDate: '2023-01-05',
    updatedDate: '2023-01-06',
    method: 'exchange',
  },
  {
    imageUrl: '/images/image2.png',
    nickName: 'Nick4',
    id: 4,
    userId: 4,
    name: 'Card4',
    price: 400,
    grade: 'legendary',
    genre: 'Romance',
    totalQuantity: 250,
    remainingQuantity: 125,
    createdDate: '2023-01-07',
    updatedDate: '2023-01-08',
    method: 'sale',
  },
  {
    imageUrl: '/images/image2.png',
    nickName: 'Nick49',
    id: 5,
    userId: 5,
    name: 'Card49',
    price: 4900,
    grade: 'common',
    genre: 'Adventure',
    totalQuantity: 490,
    remainingQuantity: 245,
    createdDate: '2023-02-05',
    updatedDate: '2023-02-06',
    method: 'sale',
  },
]
