import type { Metadata } from 'next'
import './_styles/reset.css'
import './_styles/globals.css'

import JotaiProviders from './JotaiProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <JotaiProviders>
          <div id="modal-root" />
          <div>{children}</div>
        </JotaiProviders>
      </body>
    </html>
  )
}
